# Generated by Django 3.2.9 on 2021-12-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creacion del equipo'),
        ),
    ]
