# Generated by Django 4.0 on 2021-12-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_productbacklog_project_alter_project_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbacklog',
            name='name',
            field=models.CharField(default=1, max_length=60, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbacklog',
            name='priority',
            field=models.CharField(choices=[('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], max_length=5, verbose_name='Prioridad'),
        ),
    ]
