# Generated by Django 3.2.9 on 2021-12-09 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20211209_0556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=40, verbose_name='Estado del sprint')),
                ('responsable', models.CharField(max_length=10, verbose_name='Responsable del spriint')),
                ('number_sprint', models.IntegerField(blank=True, verbose_name='Numero del sprint')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalizacion')),
                ('version', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('points_of_effort', models.IntegerField(verbose_name='Puntos de esfuerzo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('estimated_end_date', models.DateField(verbose_name='Fecha estimada de finalizacion')),
                ('final_end_date', models.DateField(verbose_name='Fecha de finalizacion')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('problems_found', models.TextField(blank=True, verbose_name='Problemas')),
                ('state', models.CharField(choices=[('ST', 'Starting'), ('PO', 'In progress'), ('DE', 'Detained'), ('FI', 'Finished')], max_length=5, verbose_name='Estado')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint', verbose_name='Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSprintUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_sprinnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.tasksprint', verbose_name='Tareas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SprintReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('hour', models.CharField(max_length=10, verbose_name='Hora')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('place', models.CharField(max_length=15, verbose_name='Lugar')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('problems', models.TextField(blank=True, verbose_name='Problemas')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint', verbose_name='Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='SprintRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha del sprint retrospective')),
                ('place', models.CharField(max_length=15, verbose_name='Lugar')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='SprintPlannig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha del sprint planning')),
                ('place', models.CharField(max_length=15, verbose_name='Lugar')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('product_backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.productbacklog', verbose_name='Product backlog')),
            ],
        ),
        migrations.AddField(
            model_name='sprint',
            name='sprint_planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.sprintplannig', verbose_name='Spring planning'),
        ),
        migrations.CreateModel(
            name='DailyScrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('hour', models.CharField(max_length=10, verbose_name='Hora')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('place', models.CharField(max_length=15, verbose_name='Lugar')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprints.sprint', verbose_name='Sprint')),
            ],
        ),
    ]
