# Generated by Django 4.0 on 2021-12-16 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_productbacklog_project_alter_project_team_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintretrospective',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='tasksprintuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario'),
        ),
    ]
