# Generated by Django 3.2.9 on 2021-12-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='telefono',
            new_name='phone',
        ),
    ]
