# Generated by Django 3.2.9 on 2021-12-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211209_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='logo',
            field=models.ImageField(null=True, upload_to='UserImages'),
        ),
    ]
