# Generated by Django 3.2.9 on 2021-12-12 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_data_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='data', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
