# Generated by Django 3.2.9 on 2021-12-14 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='teamuser',
            name='state',
            field=models.CharField(choices=[('AC', 'Active'), ('WA', 'Waiting'), ('DE', 'Deactivated')], default='DE', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_userT', to='teams.team', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_userU', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
