# Generated by Django 3.2.9 on 2021-12-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20211214_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creacion del equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='LogoTeams'),
        ),
    ]
