# Generated by Django 4.0 on 2021-12-16 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0003_auto_20211214_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_userU', to='auth.user', verbose_name='Usuario'),
        ),
    ]
